### ISSUE TITLE
Error when running script with credentials

### ISSUE THREAD

**Issue by assafelovic** [Makepad-fr/fbjs#26] opened 2021-03-03 09:01 UTC
1. Everything is installed correctly (version 2.3.2)
2. Added credentials (fgps init)

Running with this example: `fgps --group-ids 196322762283544  --output /path`

get this error: 

`(node:45896) UnhandledPromiseRejectionWarning: TimeoutError: waiting for XPath "//button[@data-cookiebanner="accept_button"]" failed: timeout 30000ms exceeded
    at new WaitTask (/Users/assafelovic/.nvm/versions/node/v12.9.1/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/Users/assafelovic/.nvm/versions/node/v12.9.1/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForXPath (/Users/assafelovic/.nvm/versions/node/v12.9.1/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:441:17)
    at Frame.waitForXPath (/Users/assafelovic/.nvm/versions/node/v12.9.1/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/FrameManager.js:642:47)
    at Frame.<anonymous> (/Users/assafelovic/.nvm/versions/node/v12.9.1/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForXPath (/Users/assafelovic/.nvm/versions/node/v12.9.1/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/Page.js:1131:29)
    at facebookLogIn (/Users/assafelovic/.nvm/versions/node/v12.9.1/lib/node_modules/facebook-group-posts-scraper/src/index.js:331:14)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async main (/Users/assafelovic/.nvm/versions/node/v12.9.1/lib/node_modules/facebook-group-posts-scraper/src/index.js:608:10)
(node:45896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:45896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by gohjiayi** [comment] 2021-03-08 16:46
Same error faced here please help! Appreciate the codes that you guys built and hope to be able to leverage on it!

```
C:\Users\Jiayi\Documents>fgps --group-ids 859169247578150 --output C:/Users/Jiayi/Desktop
(node:4396) UnhandledPromiseRejectionWarning: TimeoutError: waiting for XPath "//button[@data-cookiebanner="accept_button"]" failed: timeout 30000ms exceeded
    at new WaitTask (C:\Users\Jiayi\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (C:\Users\Jiayi\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\DOMWorld.js:478:22)
    at DOMWorld.waitForXPath (C:\Users\Jiayi\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\DOMWorld.js:441:17)
    at Frame.waitForXPath (C:\Users\Jiayi\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\FrameManager.js:642:47)
    at Frame.<anonymous> (C:\Users\Jiayi\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\helper.js:112:23)
    at Page.waitForXPath (C:\Users\Jiayi\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\Page.js:1131:29)
    at facebookLogIn (C:\Users\Jiayi\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\src\index.js:331:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4396) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kaanyagci** [comment] 2021-03-18 23:50
Hi @gohjiayi  & @assafelovic ,

Sorry for the late response! And thank you very much for your contributions. I'll check this out as soon as possible.

**Comment by hamhamhammchamm** [comment] 2021-03-22 06:08
Getting the same error as well.

**Comment by wgicio** [comment] 2021-03-23 05:11
Getting the same error as well.

**Comment by kaanyagci** [comment] 2021-03-23 13:36
@hamhamhammchamm Can you try with the branch [gh-26](https://github.com/Makepad-fr/fbjs/tree/gh-26)

**Comment by fredzannarbor** [comment] 2021-03-24 01:49
tried on branch gh-26, still got same error

 04963 --output gpt3group
(node:14929) UnhandledPromiseRejectionWarning: TimeoutError: waiting for XPath "//button[@data-cookiebanner="accept_button"]" failed: timeout 30000ms exceeded
    at new WaitTask (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForXPath (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:441:17)
    at Frame.waitForXPath (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/FrameManager.js:642:47)
    at Frame.<anonymous> (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForXPath (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/Page.js:1131:29)
    at facebookLogIn (/usr/local/lib/node_modules/facebook-group-posts-scraper/src/index.js:331:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/usr/local/lib/node_modules/facebook-group-posts-scraper/src/index.js:608:10)
(node:14929) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14929) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hamhamhammchamm** [comment] 2021-03-24 04:39
Same as above, tried it again and still got the same error.

**Comment by wgicio** [comment] 2021-03-25 04:11
`macca@macca:~$ fgps --group-ids 1775258645956385 --output /home/macca/Documents
(node:28974) UnhandledPromiseRejectionWarning: TimeoutError: waiting for XPath "//button[@data-cookiebanner="accept_button"]" failed: timeout 30000ms exceeded
    at new WaitTask (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForXPath (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:441:17)
    at Frame.waitForXPath (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/FrameManager.js:642:47)
    at Frame.<anonymous> (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForXPath (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/Page.js:1131:29)
    at facebookLogIn (/usr/local/lib/node_modules/facebook-group-posts-scraper/src/index.js:331:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:28974) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28974) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`

**Comment by kaanyagci** [comment] 2021-03-26 00:13
Thank you, @fredzannarbor @hamhamhammchamm  and @wgicio, for your responses. And I'm sorry for that issue persisted. I just double-checked, and there was a syntax error on the `try/catch` block that I've added. I fixed the syntax error and pushed [5384cba](https://github.com/Makepad-fr/fbjs/pull/27/commits/5384cbac1d12b2eec56c70c168705816fe584b6a) on the [gh-26](https://github.com/Makepad-fr/fbjs/issues/26). This will hopefully fix the issue. Please test with the latest version of the  [gh-26](https://github.com/Makepad-fr/fbjs/issues/26) branch and tell me if it works. 

Again, I can not test on my own as in Europe, the cookie banner appears.

**Comment by hamhamhammchamm** [comment] 2021-03-26 03:13
> 
> 
> Thank you, @fredzannarbor @hamhamhammchamm and @wgicio, for your responses. And I'm sorry for that issue persisted. I just double-checked, and there was a syntax error on the `try/catch` block that I've added. I fixed the syntax error and pushed [5384cba](https://github.com/Makepad-fr/fbjs/pull/27/commits/5384cbac1d12b2eec56c70c168705816fe584b6a) on the [gh-26](https://github.com/Makepad-fr/fbjs/issues/26). This will hopefully fix the issue. Please test with the latest version of the [gh-26](https://github.com/Makepad-fr/fbjs/issues/26) branch and tell me if it works.
> 
> Again, I can not test on my own as in Europe, the cookie banner appears.

Hi, I am getting a different error this time,

` UnhandledPromiseRejectionWarning: Error: Browser is not downloaded. Run "npm install" or "yarn install"
`

I installed puppeteer and chromium already but seems I'm getting the same error.

**Comment by kaanyagci** [comment] 2021-03-26 06:26
Hi @hamhamhammchamm ,

This is weird I'll take a deeper look into it. Are you running on an AWS Lambda? Also, did you try to Install the `puppeteer` instance globally with `sudo npm install puppeteer --unsafe-perm=true --allow-root` maybe it can help

**Comment by wgicio** [comment] 2021-03-26 07:35
macca@macca:~$ fgps init
? facebook username: xxxxxx
? password: [hidden]
macca@macca:~$ fgps --group-ids 1775258645956385 --output /home/macca/Documents
Cookie banner did not appear

**Comment by kaanyagci** [comment] 2021-03-26 11:25
Hi @wgicio,

The "Cookie banner did not appear" will be removed when released. But if you are having this log, the issue is fixed, right? Once you confirm, I'll publish the new version with this fix.

**Comment by hamhamhammchamm** [comment] 2021-03-26 12:35
> Hi @hamhamhammchamm ,
> 
> This is weird I'll take a deeper look into it. Are you running on an AWS Lambda? Also, did you try to Install the `puppeteer` instance globally with `sudo npm install puppeteer --unsafe-perm=true --allow-root` maybe it can help

No not using AWS Lambda. I have installed puppeteer that way but did not work.

Here's the full error for your reference.

`(node:3248) UnhandledPromiseRejectionWarning: Error: Browser is not downloaded. Run "npm install" or "yarn install"
    at ChromeLauncher.launch (C:\Users\xx\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\Launcher.js:236:15)
    at async createBrowser (C:\Users\xx\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\src\index.js:262:19)
    at async main (C:\Users\xx\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\src\index.js:605:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by kaanyagci** [comment] 2021-03-26 12:51
Hi @hamhamhammchamm ,

I'll try to check this before the end of the day.

**Comment by kaanyagci** [comment] 2021-03-26 21:33
@hamhamhammchamm just checked again. It seems like the issue is related to bundled chromium which came with the `puppeteer`. Using Google Chrome instead of bundled chromium can be a workaround:

```js
const browser = await puppeteer.launch({
    executablePath: '/full/path/to/chrome'
});
``` 

Also, you can use the [fbjs-container](https://github.com/Makepad-fr/fbjs-container).

**Comment by kaanyagci** [comment] 2021-03-26 21:41
This issue is closed as I assume the main issue related to the cookie banner is resolved. Feel free to reopen it if the issue persists.

**Comment by fredzannarbor** [comment] 2021-03-26 21:43
Not resolved for me.  I am only doing this:

fred@Freds-MacBook-Pro:~/bin/nimble/fbjs$ !1958
```
**fgps --group-ids 781481526004963 --output gpt3group**
(node:8860) UnhandledPromiseRejectionWarning: TimeoutError: waiting for XPath "//button[@data-cookiebanner="accept_button"]" failed: timeout 30000ms exceeded
    at new WaitTask (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForXPath (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/DOMWorld.js:441:17)
    at Frame.waitForXPath (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/FrameManager.js:642:47)
    at Frame.<anonymous> (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForXPath (/usr/local/lib/node_modules/facebook-group-posts-scraper/node_modules/puppeteer/lib/Page.js:1131:29)
    at facebookLogIn (/usr/local/lib/node_modules/facebook-group-posts-scraper/src/index.js:331:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/usr/local/lib/node_modules/facebook-group-posts-scraper/src/index.js:608:10)
(node:8860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kaanyagci** [comment] 2021-03-26 23:50
@fredzannarbor 

Did you tested with the version `2.4.0` that I've recently deployed on npm ?

**Comment by wgicio** [comment] 2021-03-27 02:23
it works, thanks!

**Comment by kaanyagci** [comment] 2021-03-27 21:15
You're welcome! As confirmed I'll close the issue. Feel free to re-open or open an other issue

**Closed by kaanyagci** 2021-03-27 21:15 UTC
Labels: bug

**Comment by fredzannarbor** [comment] 2021-03-27 21:32
thanks!
---
